# Site settings
title: Thomas Salmon, Blog
email: ths871@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  french techie
baseurl: "" # the subpath of your site, e.g. /blog/
url: "tsalmon.github.io" # the base hostname & protocol for your site
twitter_username: th_s75
github_username:  tsalmon

paginate: 1
# Build settings
markdown: kramdown
